Brenner/devtools
darkforest-eth/plugins pull request #10
Opened 2020-12-30 20:44 UTC by BrennerSpear

Makes importing df-related utils into your console as easy as clicking a button.
Also added Artifactory utils to the utils fiile

2020-12-31 02:03 UTC, phated requested changes
Very cool. I love how this will improve the prototype experience. I didn't account for UI-less plugins in the showcase, so maybe put the console.log message into the UI and take a screenshot?

2020-12-31 02:03 UTC, phated commented on javascript/utils/utils.js
> +}
This naming is actually false advertising and was causing a bug in artifactory. Can you snag the new methods/names from the latest version I made available? I think the name of this became `myPlanetsWithFindable` and I added the correct implementation for `myPlanetsWithArtifacts`

2020-12-31 02:03 UTC, phated commented on javascript/utils/utils.js
> +export let calcBonus = (bonus) => {
let's rename to
```suggestion
export let calcArtifactBonus = (bonus) => {
```

2020-12-31 02:03 UTC, phated commented on javascript/utils/utils.js
> +export let canDeposit = (planet) => {
let's rename to
```suggestion
export let canDepositArtifact = (planet) => {
```

2021-01-19 18:58 UTC, jacobrosenthal commented
Always happy to have it reopened

2021-01-19 18:58 UTC, closed without merging