Add Plugin: Aritifact Automove
darkforest-eth/plugins pull request #158
Opened 2021-08-26 04:38 UTC by thickforest

Deactivate the artifact and auto move it to spacetime rip, and then withdraw it.

2021-08-28 20:48 UTC, Stx69 approved these changes

2021-08-30 14:02 UTC, thickforest reviewed
I have made some changes, and now the plugins can reach the limits: 
(1) 6 pending + unconfirmed moves
(2) 5 pending + unconfirmed moves + heldArtifactNum

2021-09-02 09:41 UTC, davidryan59 requested changes
Plugin looks good. Haven't had opportunity to test yet, I have no active artifacts to withdraw currently!

A few minor fixes please?

2021-09-02 09:41 UTC, davidryan59 commented on content/artifacts/artifact-automove/plugin.js
> +        if (Date.now() > (artifact.lastDeactivated + 48 * 60 * 60) * 1000) {
Can we refactor 48 * 60 * 60 as a constant listed at the top of the file please, so it can be easily updated?

2021-09-02 09:41 UTC, davidryan59 commented on content/artifacts/artifact-automove/plugin.js
> +      if (Date.now() > (artifact.lastDeactivated + 24 * 60 * 60) * 1000) {
Can we refactor 24 * 60 * 60 as a constant listed at the top of the file please, so it can be easily updated?

2021-09-02 09:41 UTC, davidryan59 commented on content/artifacts/artifact-automove/plugin.js
> +    this.deactiveArtifactIfNeeded = false;
Fix typo - please can `this.deactiveArtifactIfNeeded` be renamed to `this.deactivateArtifactIfNeeded` here and throughout the file?

2021-09-02 09:41 UTC, davidryan59 commented on content/artifacts/artifact-automove/plugin.js
> +    let deactiveArtifactLabel = document.createElement('label');
Fix typo - please can we update `deactiveArtifactLabel` to `deactivateArtifactLabel`? 5 instances in file.

2021-09-02 09:43 UTC, davidryan59 commented on content/artifacts/artifact-automove/plugin.js
> +        if (Date.now() > (artifact.lastDeactivated + 48 * 60 * 60) * 1000) {
In future rounds this value might change, so with a constant at the top of the file this can easily be found and updated.

2021-09-03 15:39 UTC, jacobrosenthal commented on content/artifacts/artifact-automove/plugin.js
> +      if (unconfirmed + arrivals + heldArtifactNum > 4) {
These arrivals dont necessarily have artifacts, theyre just general arrivals.  You would have to be check to see if that arrival includes an artifact

2021-09-03 16:20 UTC, jacobrosenthal commented on content/artifacts/artifact-automove/plugin.js
> +      if (unconfirmed + arrivals + heldArtifactNum > 4) {
Looks like the contract enforces >5+1, or 5 total artifacts?
https://github.com/darkforest-eth/eth/blob/dd27511f35d82dd6539b74078e689349b9525279/contracts/DarkForestPlanet.sol#L416-L421

2021-09-04 13:09 UTC, jacobrosenthal commented on content/artifacts/artifact-automove/plugin.js
> +      const arrivalArtifacts = arrivalArtifacts.filter(arrival = > arrival.artifactId);
```
Failed to start plugin: autmover - Please review stack trace
 SyntaxError: Unexpected token '>'
spawn @ PluginManager.tsx:211
async function (async)
spawn @ PluginManager.tsx:205
render @ PluginManager.tsx:223
(anonymous) @ OwnedPluginView.tsx:84
co @ react-dom.production.min.js:131
ds @ react-dom.production.min.js:220
_l @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ui @ react-dom.production.min.js:122
Cl @ react-dom.production.min.js:252
dl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ui @ react-dom.production.min.js:122
$i @ react-dom.production.min.js:123
Ji @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
qt @ react-dom.production.min.js:73
```
```suggestion
      const arrivalArtifacts = arrivalArtifacts.filter(arrival => arrival.artifactId);
```

2021-09-04 13:09 UTC, jacobrosenthal commented on content/artifacts/artifact-automove/plugin.js
> +      const arrivalArtifacts = arrivalArtifacts.filter(arrival = > arrival.artifactId);
```
Uncaught ReferenceError: Cannot access 'arrivalArtifacts' before initialization
    at Plugin.move (30a83f8f-9b85-481c-9003-bf95e28a4e78:125)
    at Plugin.automove (30a83f8f-9b85-481c-9003-bf95e28a4e78:197)
    at Plugin.globalAutoMove (30a83f8f-9b85-481c-9003-bf95e28a4e78:217)
```

2021-09-05 04:31 UTC, jacobrosenthal commented
A few artifacts got stuck out on random tiny planets, and I had a few reverts "	this artifact is not on this planet" but that might be the game not refreshing properly, and "Tried to move more population that what exists" but that happens in the copy pasted crawl code I think. 

Nice job!

2021-09-05 04:32 UTC, merged